networks:
  default:
    external: true # использовать созданную сеть
    name: app_network

services:
  LttfRating:
    image: lttf_rating
    restart: always
    container_name: lttf_rating    
    build:
      context: .
      dockerfile: LttfRating/Dockerfile
    volumes:
      - C:/docker/lttf_rating:/app/config
    environment:
      - ASPNETCORE_ENVIRONMENT=PROD
    networks:
      - default
